#!/bin/sh
# Jose Recinos and Matt Gottlieb
if [ $# -eq 0 ]; then
    echo "usage: $0 directory"
    exit 1
fi
if [ -f "$1" ]; then
    echo "$1 is not a directory"
    exit 4
fi

if [ ! -d "$1" ]; then
    echo "there is no directory named $1"
    exit 2
fi

if [ ! -x $1 ]; then
    echo "you do not have permission to read $1"
    exit 3
fi

echo "writable files in $1:"
find $1/ -type  f -writable  -printf "%f\n"

#Matthew Gottlieb, Jose Recinos, 11/2/2017
